apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hld-workspace.fullname" . }}-src
  namespace: {{ include "hld-workspace.namespace" . }}
  labels:
    {{- include "hld-workspace.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.srcSize }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
